In [6]:
from sklearn import datasets
import numpy as np

In [7]:
iris = datasets.load_iris()
iris_X = iris.data
masking_array = np.random.binomial(1, .25, 
                    iris_X.shape).astype(bool)
iris_X[masking_array] = np.nan

In [8]:
masking_array[:5]

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [False, False,  True, False],
       [ True, False, False,  True]], dtype=bool)

In [10]:
iris_X[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  nan,  nan],
       [ 4.6,  3.1,  nan,  0.2],
       [ nan,  3.6,  1.4,  nan]])

In [11]:
from sklearn import preprocessing

In [12]:
impute = preprocessing.Imputer()

In [13]:
iris_X_prime = impute.fit_transform(iris_X)

In [14]:
iris_X_prime[:5]

array([[ 5.1       ,  3.5       ,  1.4       ,  0.2       ],
       [ 4.9       ,  3.        ,  1.4       ,  0.2       ],
       [ 4.7       ,  3.2       ,  3.89122807,  1.23853211],
       [ 4.6       ,  3.1       ,  3.89122807,  0.2       ],
       [ 5.83846154,  3.6       ,  1.4       ,  1.23853211]])

In [15]:
iris_X_prime[3, 0]

4.5999999999999996

In [16]:
iris_X[3, 0]

4.5999999999999996

In [17]:
impute = preprocessing.Imputer(strategy='median')
iris_X_prime = impute.fit_transform(iris_X)
iris_X_prime[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  4.4,  1.4],
       [ 4.6,  3.1,  4.4,  0.2],
       [ 5.7,  3.6,  1.4,  1.4]])

In [18]:
iris_X[np.isnan(iris_X)] = -1
iris_X[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2, -1. , -1. ],
       [ 4.6,  3.1, -1. ,  0.2],
       [-1. ,  3.6,  1.4, -1. ]])

In [23]:
import pandas as pd
iris_X[masking_array] = np.nan

In [24]:
iris_df = pd.DataFrame(iris_X, columns=iris.feature_names)

In [26]:
iris_df.fillna(iris_df.mean())['sepal length (cm)'].head(5)

0    5.100000
1    4.900000
2    4.700000
3    4.600000
4    5.838462
Name: sepal length (cm), dtype: float64

In [28]:
iris_df.fillna(iris_df.max())['sepal length (cm)'].head(5)

0    5.1
1    4.9
2    4.7
3    4.6
4    7.9
Name: sepal length (cm), dtype: float64