# Scaling data to the standard normal

In [22]:
from sklearn import datasets
boston = datasets.load_boston()

In [23]:
X, y = boston.data, boston.target

In [24]:
from sklearn import preprocessing
import numpy as np

In [25]:
X[:, :3].mean(axis=0)

array([  3.59376071,  11.36363636,  11.13677866])

In [26]:
X[:, :3].std(axis=0)

array([  8.58828355,  23.29939569,   6.85357058])

In [27]:
X_2 = preprocessing.scale(X[:, :3])

In [28]:
X_2.mean(axis=0)

array([  6.34099712e-17,  -6.34319123e-16,  -2.68291099e-15])

In [29]:
X_2.std(axis=0)

array([ 1.,  1.,  1.])

In [30]:
my_scaler = preprocessing.StandardScaler()

In [31]:
my_scaler.fit(X[:, :3])

StandardScaler(copy=True, with_mean=True, with_std=True)

In [32]:
my_scaler.transform(X[:, :3]).mean(axis=0)

array([  6.34099712e-17,  -6.34319123e-16,  -2.68291099e-15])

In [33]:
my_minmax_scaler = preprocessing.MinMaxScaler()
my_minmax_scaler.fit(X[:, :3])
my_minmax_scaler.transform(X[:, :3]).max(axis=0)

array([ 1.,  1.,  1.])

In [34]:
my_odd_scaler = preprocessing.MinMaxScaler(feature_range=(-3.14, 3.14))

In [35]:
normalized_X = preprocessing.normalize(X[:, :3])

In [36]:
my_useless_scaler = preprocessing.StandardScaler(with_mean=False, 
                                                     with_std=False)
transformed_sd = my_useless_scaler.fit_transform(X[:, :3]).std(axis=0)
    
original_sd = X[:, :3].std(axis=0)
    np.array_equal(transformed_sd, original_sd)

True

In [6]:
X, y = boston.data, boston.target