In [77]:
#library objjects and functions

#ML specific
from sklearn import datasets as d
from sklearn import preprocessing
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.preprocessing import LabelBinarizer

In [3]:
# Getting sample data from external sources

#pre-installed with scikit library
boston = d.load_boston() 

#download with scikit-learn
housing = d.fetch_california_housing()

downloading Cal. housing from http://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.tgz to /home/manavee/scikit_learn_data


In [11]:
#Creating sample data for toy analysis
    # Generate a random regression problem.
        # make_regression(n_samples=100, n_features=100, n_informative=10, n_targets=1, bias=0.0, effective_rank=None, tail_strength=0.5, noise=0.0, shuffle=True, coef=False, random_state=None)
    # Generate a random n-class classification problem
        # make_classification(n_samples=100, n_features=20, n_informative=2, n_redundant=2, n_repeated=0, n_classes=2, n_clusters_per_class=2, weights=None, flip_y=0.01, class_sep=1.0, hypercube=True, shift=0.0, scale=1.0, shuffle=True, random_state=None)
    # Generate isotropic Gaussian blobs for clustering
        #make_blobs(n_samples=100, n_features=2, centers=3, cluster_std=1.0, center_box=(-10.0, 10.0), shuffle=True, random_state=None)
    # datasets.make_biclusters
    # datasets.make_blobs
    # datasets.make_checkerboard
    # datasets.make_circles
    # datasets.make_classification
    # datasets.make_friedman1
    # datasets.make_friedman2
    # datasets.make_friedman3
    # datasets.make_gaussian_quantiles
    # datasets.make_hastie_10_2
    # datasets.make_low_rank_matrix
    # datasets.make_moons
    # datasets.make_multilabel_classification
    # datasets.make_regression
    # datasets.make_s_curve
    # datasets.make_sparse_coded_signal
    # datasets.make_sparse_spd_matrix
    # datasets.make_sparse_uncorrelated
    # datasets.make_spd_matrix
    # datasets.make_swiss_roll        

complex_reg_data = d.make_regression(1000, 10, 5, 2, 1.0)
classification_set = d.make_classification(weights=[0.2])
Xs,Ys = d.make_blobs()

#bincount(x, weights=None, minlength=None)
    #Count number of occurrences of each value in array of non-negative ints
np.bincount(classification_set[1])



array([20, 80])

In [52]:
#Scaling data to the standard normal
    #MinMaxScaler()
        #arr_scaled = arr_std * (arr_max - arr_min) + arr_min
        #use feature_range=(min,max) for defining new min,max
    #StandardScaler()
         #Standardize features by removing the mean and scaling to unit variance
         #x = ( x - mean(X) )/ std(X)

X, y = boston.data, boston.target
print(X[:, :3].mean(axis=0)) # mean of first 3 columns
print(X[:, :3].std(axis=0)) #standard deviation first 3 columns
scaler = preprocessing.StandardScaler()
print(scaler.fit(X[:, :3]).transform(X[:, :3]).mean(axis=0))

[  3.59376071  11.36363636  11.13677866]
[  8.58828355  23.29939569   6.85357058]
[  6.34099712e-17  -6.34319123e-16  -2.68291099e-15]


In [ ]:
# >--> Creating binary features through thresholding
#   What:
#       -Instead of working with the distribution to standardize it, we'll purposely throw away data
#   Why:
#      -Often, in what is ostensibly continuous data, there are discontinuities that can be determined via binary features
#   How:
#         preprocessing.binarize #(a function)
#         preprocessing.Binarizer #(a class)
#   When:
#         -Convert continous feature to categorical

# If the value is greater than the threshold i.e mean, produce a 1; if it is less, produce a 0:
new_target = preprocessing.binarize(boston.target, threshold=boston.target.mean())


In [74]:
# text_encoder = preprocessing.OneHotEncoder()
#    definition:
#         Encode categorical integer features using a one-hot aka one-of-K scheme
#     input:
#          The input to this transformer should be a matrix of integers, denoting values taken on by categorical (discrete) features
#     output:
#          a sparse matrix where each column corresponds to one possible value of one feature
#     USecase:
#         Given a dataset with three features and two samples, we let the encoder find the maximum value per feature and transform the data to a binary one-hot encoding

#DictVectorizer()
#     definition:
#         -transforms lists of mappings (dict-like objects) of feature names to feature values into Numpy arrays or scipy.sparse matrices
#             -strings -> one-hot (aka one-of-K) coding


In [65]:
# >--> Working with categorical variables

iris = datasets.load_iris()
X = iris.data
y = iris.target
d = np.column_stack((X, y))
text_encoder = preprocessing.OneHotEncoder()
text_encoder.fit_transform(d[:, -1:]).toarray()[:5]
dv = DictVectorizer()
my_dict = [{'species': iris.target_names[i]} for i in y]
dv.fit_transform(my_dict).toarray()[:5]

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [62]:
#help(DictVectorizer())
dv = DictVectorizer()
my_dict = [{'species': iris.target_names[i]} for i in y]
dv.fit_transform(my_dict).toarray()[:5]

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [73]:
v = DictVectorizer()
D = [{'foo': 1, 'bar': 2}, {'foo': 3, 'baz': 1}]
X = v.fit_transform(D)
support = SelectKBest(chi2, k=2).fit(X, [0, 1])
print(v.get_feature_names())
# ['bar', 'baz', 'foo']
print(v.restrict(support.get_support())
# doctest: +ELLIPSIS
# DictVectorizer(dtype=..., separator='='sort=True,sparse=True)
print(v.get_feature_names())
# ['bar', 'foo']

SyntaxError: invalid syntax (<ipython-input-73-4eee0e9bc076>, line 10)

In [86]:
# d.load_iris()
target = iris.target
label_binarizer = LabelBinarizer()
new_target = label_binarizer.fit_transform(target)
print('target old', target[:5],
      '\n new_target.shape  ', new_target.shape,
      '\n new_target[:5]  ',new_target[:5],
      '\n label_binarizer.classes_  ',label_binarizer.classes_,
      '\n label_binarizer.transform([4])  ', label_binarizer.transform([4]),
      '\n end')

label_binarizer = LabelBinarizer(neg_label=-1000, pos_label=1000)
print(label_binarizer.fit_transform(target)[:5])

target old [0 0 0 0 0] 
 new_target.shape   (150, 3) 
 new_target[:5]   [[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]] 
 label_binarizer.classes_   [0 1 2] 
 label_binarizer.transform([4])   [[0 0 0]] 
 end
[[ 1000 -1000 -1000]
 [ 1000 -1000 -1000]
 [ 1000 -1000 -1000]
 [ 1000 -1000 -1000]
 [ 1000 -1000 -1000]]


In [87]:
>--> Imputing missing values through various strategies:
    -Imputation transformer for completing missing values
    -preprocessing.Imputer(missing_values='NaN', strategy='mean', axis=0, verbose=0, copy=True)
        -strategy- "mean"/"median"/"most_frequent"
        
    

In [103]:
iris_X = iris.data
masking_array = np.random.binomial(1, .25, 
                    iris_X.shape).astype(bool)
iris_X[masking_array] = np.nan
print(masking_array[:5])
print(iris_X[:5])
impute = preprocessing.Imputer(strategy='median')
iris_X_prime = impute.fit_transform(iris_X)
print(iris_X_prime[:5])

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False  True  True  True]
 [False  True False False]]
[[ nan -1.   1.4  0.2]
 [ 4.9  nan -1.   0.2]
 [-1.  -1.   nan -1. ]
 [-1.   nan  nan  nan]
 [-1.   nan  1.4 -1. ]]
[[-1.  -1.   1.4  0.2]
 [ 4.9 -1.  -1.   0.2]
 [-1.  -1.  -1.  -1. ]
 [-1.  -1.  -1.  -1. ]
 [-1.  -1.   1.4 -1. ]]


In [101]:
astype?
pd.DataFrame.fillna?

Object `astype` not found.
